type RowObj = {
  id: number;
  name: string;
  status: string;
  mailaddress: string;
  date: string;
  price: number;
};

const tableDataComplex: RowObj[] = [
  {
    id: 1,
    name: 'Horizon UI PRO',
    mailaddress: 'horizon.pro@example.com',
    status: 'Approved',
    date: '12 Jan 2021',
    price: 1234,
  },
  {
    id: 2,
    name: 'Horizon UI Free',
    mailaddress: 'horizon.free@example.com',
    status: 'Disable',
    date: '21 Feb 2021',
    price: 2345,
  },
  {
    id: 3,
    name: 'Weekly Update',
    mailaddress: 'weekly.update@example.com',
    status: 'Error',
    date: '13 Mar 2021',
    price: 3456,
  },
  {
    id: 4,
    name: 'Marketplace',
    mailaddress: 'marketplace@example.com',
    status: 'Approved',
    date: '24 Oct 2022',
    price: 4567,
  },
  {
    id: 5,
    name: 'Project Alpha',
    mailaddress: 'project.alpha@example.com',
    status: 'In Progress',
    date: '15 Apr 2021',
    price: 5678,
  },
  {
    id: 6,
    name: 'Project Beta',
    mailaddress: 'project.beta@example.com',
    status: 'Approved',
    date: '20 May 2021',
    price: 6789,
  },
  {
    id: 7,
    name: 'Project Gamma',
    mailaddress: 'project.gamma@example.com',
    status: 'Pending',
    date: '10 Jun 2021',
    price: 7890,
  },
  {
    id: 8,
    name: 'Project Delta',
    mailaddress: 'project.delta@example.com',
    status: 'Disable',
    date: '05 Jul 2021',
    price: 8901,
  },
  {
    id: 9,
    name: 'Project Epsilon',
    mailaddress: 'project.epsilon@example.com',
    status: 'Error',
    date: '25 Aug 2021',
    price: 9012,
  },
  {
    id: 10,
    name: 'Project Zeta',
    mailaddress: 'project.zeta@example.com',
    status: 'Approved',
    date: '15 Sep 2021',
    price: 1234,
  },
  {
    id: 11,
    name: 'Project Eta',
    mailaddress: 'project.eta@example.com',
    status: 'In Progress',
    date: '05 Oct 2021',
    price: 2345,
  },
  {
    id: 12,
    name: 'Project Theta',
    mailaddress: 'project.theta@example.com',
    status: 'Pending',
    date: '25 Nov 2021',
    price: 3456,
  },
  {
    id: 13,
    name: 'Project Iota',
    mailaddress: 'project.iota@example.com',
    status: 'Disable',
    date: '15 Dec 2021',
    price: 4567,
  },
  {
    id: 14,
    name: 'Project Kappa',
    mailaddress: 'project.kappa@example.com',
    status: 'Error',
    date: '05 Jan 2022',
    price: 5678,
  },
  {
    id: 15,
    name: 'Project Lambda',
    mailaddress: 'project.lambda@example.com',
    status: 'Approved',
    date: '25 Feb 2022',
    price: 6789,
  },
  {
    id: 16,
    name: 'Project Mu',
    mailaddress: 'project.mu@example.com',
    status: 'In Progress',
    date: '15 Mar 2022',
    price: 7890,
  },
  {
    id: 17,
    name: 'Project Nu',
    mailaddress: 'project.nu@example.com',
    status: 'Pending',
    date: '05 Apr 2022',
    price: 8901,
  },
  {
    id: 18,
    name: 'Project Xi',
    mailaddress: 'project.xi@example.com',
    status: 'Disable',
    date: '25 May 2022',
    price: 9012,
  },
  {
    id: 19,
    name: 'Project Omicron',
    mailaddress: 'project.omicron@example.com',
    status: 'Error',
    date: '15 Jun 2022',
    price: 1234,
  },
  {
    id: 20,
    name: 'Project Pi',
    mailaddress: 'project.pi@example.com',
    status: 'Approved',
    date: '05 Jul 2022',
    price: 2345,
  },
  {
    id: 21,
    name: 'Project Rho',
    mailaddress: 'project.rho@example.com',
    status: 'In Progress',
    date: '25 Aug 2022',
    price: 3456,
  },
  {
    id: 22,
    name: 'Project Sigma',
    mailaddress: 'project.sigma@example.com',
    status: 'Pending',
    date: '15 Sep 2022',
    price: 4567,
  },
  {
    id: 23,
    name: 'Project Tau',
    mailaddress: 'project.tau@example.com',
    status: 'Disable',
    date: '05 Oct 2022',
    price: 5678,
  },
  {
    id: 24,
    name: 'Project Upsilon',
    mailaddress: 'project.upsilon@example.com',
    status: 'Error',
    date: '25 Nov 2022',
    price: 6789,
  },
  {
    id: 25,
    name: 'Project Phi',
    mailaddress: 'project.phi@example.com',
    status: 'Approved',
    date: '15 Dec 2022',
    price: 7890,
  },
  {
    id: 26,
    name: 'Project Chi',
    mailaddress: 'project.chi@example.com',
    status: 'In Progress',
    date: '05 Jan 2023',
    price: 8901,
  },
  {
    id: 27,
    name: 'Project Psi',
    mailaddress: 'project.psi@example.com',
    status: 'Pending',
    date: '25 Feb 2023',
    price: 9012,
  },
  {
    id: 28,
    name: 'Project Omega',
    mailaddress: 'project.omega@example.com',
    status: 'Disable',
    date: '15 Mar 2023',
    price: 1234,
  },
  {
    id: 29,
    name: 'Project Alpha 2',
    mailaddress: 'project.alpha2@example.com',
    status: 'Error',
    date: '05 Apr 2023',
    price: 2345,
  },
  {
    id: 30,
    name: 'Project Beta 2',
    mailaddress: 'project.beta2@example.com',
    status: 'Approved',
    date: '25 May 2023',
    price: 3456,
  },
  {
    id: 31,
    name: 'Project Gamma 2',
    mailaddress: 'project.gamma2@example.com',
    status: 'In Progress',
    date: '15 Jun 2023',
    price: 4567,
  },
  {
    id: 32,
    name: 'Project Delta 2',
    mailaddress: 'project.delta2@example.com',
    status: 'Pending',
    date: '05 Jul 2023',
    price: 5678,
  },
  {
    id: 33,
    name: 'Project Epsilon 2',
    mailaddress: 'project.epsilon2@example.com',
    status: 'Disable',
    date: '25 Aug 2023',
    price: 6789,
  },
  {
    id: 34,
    name: 'Project Zeta 2',
    mailaddress: 'project.zeta2@example.com',
    status: 'Error',
    date: '15 Sep 2023',
    price: 7890,
  },
  {
    id: 35,
    name: 'Project Eta 2',
    mailaddress: 'project.eta2@example.com',
    status: 'Approved',
    date: '05 Oct 2023',
    price: 8901,
  },
  {
    id: 36,
    name: 'Project Theta 2',
    mailaddress: 'project.theta2@example.com',
    status: 'In Progress',
    date: '25 Nov 2023',
    price: 9012,
  },
  {
    id: 37,
    name: 'Project Iota 2',
    mailaddress: 'project.iota2@example.com',
    status: 'Pending',
    date: '15 Dec 2023',
    price: 1234,
  },
  {
    id: 38,
    name: 'Project Kappa 2',
    mailaddress: 'project.iotakjhsdjh2@example.com',
    status: 'Disable',
    date: '05 Jan 2024',
    price: 2345,
  },
  {
    id: 39,
    name: 'Project Lambda 2',
    mailaddress: 'project.lambda2@example.com',
    status: 'Error',
    date: '25 Feb 2024',
    price: 3456,
  },
];
export default tableDataComplex;
